# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3e178e9d5106a7ad0fd24613a9949c745a641ee4e562c66cac27c9599f84d72bf47cb1a9b84de959dc6ab83abb53c2dda8e14dbab9b220ec0b09a62d975d5e2

test:
  secret_key_base: 253be5a47da5218603b16ebb95c2e4e2e153afa84e1db78bd903605eb774cfa5a6e5755a0238570149ce1f9a4f9ad0f6fda8863f4a4cdbd3589c2c109ca33bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
